name: CD - Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Build and push Docker image
        run: |
          # Pull latest code is handled by the checkout
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-book-project:latest .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-book-project:latest

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/to/your/app   # Update this path to where your app is located on your server
            git pull origin main   # Optional if you are using Git; if you're deploying via Docker, this may not be needed
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-book-project:latest
            docker stop fastapi_app || true
            docker rm fastapi_app || true
            docker run -d --name fastapi_app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-book-project:latest
          EOF
